replicaCount: 2

containerPort: 8080
registry: registry.server.local:5000

namespace: pro-clicus-metrics-back

env:
  TZ: "UTC"
  MONGO_URI: "mongodb-service.pro-clicus-metrics-back.svc.cluster.local:27017"
  MONGO_USER: "clicus_user"
secrets:
  JWT_SECRET: "JWT_SECRET"
  MONGO_PASSWORD: "MONGO_PASSWORD"

resources:
  requests:
    memory: "32Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

probes:
  enabled: true
  readiness:
    enabled: false
    path: /healthz
    periodSeconds: 30
  liveness:
    enabled: false
    path: /healthz
    periodSeconds: 30
  startup:
    enabled: false
    path: /healthz
    periodSeconds: 5
    initialDelaySeconds: 10